In [11]:
import pandas as pd
import os

In [14]:
os.getcwd()

'c:\\Users\\Sahil Khan\\OneDrive\\Desktop\\AI GRAD CERT\\aidi github\\AIDI 2005 - Capstone Project II\\Fraud-Detection-in-Financial-Transactions\\notebook'

In [15]:
df = pd.read_csv('c:\\Users\\Sahil Khan\\OneDrive\\Desktop\\AI GRAD CERT\\aidi github\\AIDI 2005 - Capstone Project II\\Fraud-Detection-in-Financial-Transactions\\Data\\output_file_1.csv')

In [16]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.00,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.00,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.00,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.00,0.00,0,0
...,...,...,...,...,...,...,...,...,...,...,...
99995,10,PAYMENT,4020.66,C1410794718,159929.0,155908.34,M1257036576,0.00,0.00,0,0
99996,10,PAYMENT,18345.49,C744303677,6206.0,0.00,M1785344556,0.00,0.00,0,0
99997,10,CASH_IN,183774.91,C104331851,39173.0,222947.91,C36392889,54925.05,0.00,0,0
99998,10,CASH_OUT,82237.17,C707662966,6031.0,0.00,C1553004158,592635.66,799140.46,0,0
99999,10,PAYMENT,20096.56,C1868032458,110117.0,90020.44,M1419201886,0.00,0.00,0,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   step            100000 non-null  int64
 1   type            100000 non-null  object
 2   amount          100000 non-null  float64
 3   nameOrig        100000 non-null  object
 4   oldbalanceOrg   100000 non-null  float64
 5   newbalanceOrig  100000 non-null  float64
 6   nameDest        100000 non-null  object
 7   oldbalanceDest  100000 non-null  float64
 8   newbalanceDest  100000 non-null  float64
 9   isFraud         100000 non-null  int64
 10  isFlaggedFraud  100000 non-null  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 8.4+ MB

In [19]:
from collections import namedtuple

In [ ]:
DataIngestionConfig = namedtuple('DataIngestionConfig',["","",""])

In [7]:
import glob
import os
import pandas as pd

In [5]:
csv_files = glob.glob(os.path.join(r"C:\\Users\\Sahil Khan\\OneDrive\Desktop\AI GRAD CERT\\aidi github\AIDI 2005 - Capstone Project II\\Fraud-Detection-in-Financial-Transactions\\Data", '*.csv'))
csv_files

['C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_1.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_10.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_11.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_12.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_13.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_14.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_15.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_16.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_17.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_18.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_19.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_2.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_20.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_21.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_22.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_23.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_24.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_25.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_26.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_27.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_28.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_29.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_3.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_30.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_31.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_32.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_33.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_34.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_35.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_36.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_37.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_38.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_39.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_4.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_40.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_41.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_42.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_43.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_44.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_45.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_46.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_47.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_48.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_49.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_5.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_50.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_51.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_52.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_53.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_54.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_55.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_56.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_57.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_58.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_59.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_6.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_60.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_61.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_62.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_63.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_64.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_7.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_8.csv',
 'C:\\\\Users\\\\Sahil Khan\\\\OneDrive\\Desktop\\AI GRAD CERT\\\\aidi github\\AIDI 2005 - Capstone Project II\\\\Fraud-Detection-in-Financial-Transactions\\\\Data\\output_file_9.csv']

In [8]:
frdTrns_data = []

# Read each CSV file into a DataFrame and append it to the list
for csv_file in csv_files:
    df = pd.read_csv(csv_file)
    frdTrns_data.append(df)

AttributeError: 'list' object has no attribute 'head'

In [9]:
final_df = pd.concat(frdTrns_data, ignore_index=True)

In [11]:
final_df.head(50)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0
10,1,DEBIT,9644.94,C1900366749,4465.00,0.00,C997608398,10845.0,157982.12,0,0
11,1,PAYMENT,3099.97,C249177573,20771.00,17671.03,M2096539129,0.0,0.00,0,0
12,1,PAYMENT,2560.74,C1648232591,5070.00,2509.26,M972865270,0.0,0.00,0,0
13,1,PAYMENT,11633.76,C1716932897,10127.00,0.00,M801569151,0.0,0.00,0,0
14,1,PAYMENT,4098.78,C1026483832,503264.00,499165.22,M1635378213,0.0,0.00,0,0
15,1,CASH_OUT,229133.94,C905080434,15325.00,0.00,C476402209,5083.0,51513.44,0,0
16,1,PAYMENT,1563.82,C761750706,450.00,0.00,M1731217984,0.0,0.00,0,0
17,1,PAYMENT,1157.86,C1237762639,21156.00,19998.14,M1877062907,0.0,0.00,0,0
18,1,PAYMENT,671.64,C2033524545,15123.00,14451.36,M473053293,0.0,0.00,0,0
19,1,TRANSFER,215310.30,C1670993182,705.00,0.00,C1100439041,22425.0,0.00,0,0
20,1,PAYMENT,1373.43,C20804602,13854.00,12480.57,M1344519051,0.0,0.00,0,0
21,1,DEBIT,9302.79,C1566511282,11299.00,1996.21,C1973538135,29832.0,16896.70,0,0
22,1,DEBIT,1065.41,C1959239586,1817.00,751.59,C515132998,10330.0,0.00,0,0
23,1,PAYMENT,3876.41,C504336483,67852.00,63975.59,M1404932042,0.0,0.00,0,0
24,1,TRANSFER,311685.89,C1984094095,10835.00,0.00,C932583850,6267.0,2719172.89,0,0
25,1,PAYMENT,6061.13,C1043358826,443.00,0.00,M1558079303,0.0,0.00,0,0
26,1,PAYMENT,9478.39,C1671590089,116494.00,107015.61,M58488213,0.0,0.00,0,0
27,1,PAYMENT,8009.09,C1053967012,10968.00,2958.91,M295304806,0.0,0.00,0,0
28,1,PAYMENT,8901.99,C1632497828,2958.91,0.00,M33419717,0.0,0.00,0,0
29,1,PAYMENT,9920.52,C764826684,0.00,0.00,M1940055334,0.0,0.00,0,0
30,1,PAYMENT,3448.92,C2103763750,0.00,0.00,M335107734,0.0,0.00,0,0
31,1,PAYMENT,4206.84,C215078753,0.00,0.00,M1757317128,0.0,0.00,0,0
32,1,PAYMENT,5885.56,C840514538,0.00,0.00,M1804441305,0.0,0.00,0,0
33,1,PAYMENT,5307.88,C1768242710,0.00,0.00,M1971783162,0.0,0.00,0,0
34,1,PAYMENT,5031.22,C247113419,0.00,0.00,M151442075,0.0,0.00,0,0
35,1,PAYMENT,24213.67,C1238616099,0.00,0.00,M70695990,0.0,0.00,0,0
36,1,PAYMENT,8603.42,C1608633989,253.00,0.00,M1615617512,0.0,0.00,0,0
37,1,PAYMENT,2791.42,C923341586,300481.00,297689.58,M107994825,0.0,0.00,0,0
38,1,PAYMENT,7413.54,C1470868839,297689.58,290276.03,M1426725223,0.0,0.00,0,0
39,1,PAYMENT,3295.19,C711197015,233633.00,230337.81,M1384454980,0.0,0.00,0,0
40,1,PAYMENT,1684.81,C1481594086,297.00,0.00,M1569435561,0.0,0.00,0,0
41,1,DEBIT,5758.59,C1466917878,32604.00,26845.41,C1297685781,209699.0,16997.22,0,0
42,1,CASH_OUT,110414.71,C768216420,26845.41,0.00,C1509514333,288800.0,2415.16,0,0
43,1,PAYMENT,7823.46,C260084831,998.00,0.00,M267814113,0.0,0.00,0,0
44,1,PAYMENT,5086.48,C598357562,0.00,0.00,M1593224710,0.0,0.00,0,0
45,1,PAYMENT,5281.48,C1440738283,152019.00,146737.52,M1849015357,0.0,0.00,0,0
46,1,PAYMENT,13875.98,C484199463,15818.00,1942.02,M2008106788,0.0,0.00,0,0
47,1,CASH_OUT,56953.90,C1570470538,1942.02,0.00,C824009085,70253.0,64106.18,0,0
48,1,CASH_OUT,5346.89,C512549200,0.00,0.00,C248609774,652637.0,6453430.91,0,0
49,1,PAYMENT,2204.04,C1615801298,586.00,0.00,M490391704,0.0,0.00,0,0

In [18]:
from sklearn.model_selection import StratifiedShuffleSplit

strat_train_set = None
strat_test_set = None

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

In [22]:
for train_index, test_index in split.split(final_df, final_df['isFraud']):
    strat_train_set = final_df.loc[train_index]
    strat_test_set = final_df.loc[test_index]

In [25]:
strat_test_set['isFraud'].value_counts()

0    1270881
1       1643
Name: isFraud, dtype: int64

In [17]:
final_df['isFraud'].value_counts()

0    6354407
1       8213
Name: isFraud, dtype: int64

In [ ]:


file_name = os.listdir(raw_data_dir)[0]

logging.info(f"Reading csv file: [{raw_data_dir}]")

# Initialize an empty list to store DataFrames
frdTrns_data = []

# Read each CSV file into a DataFrame and append it to the list
for csv_file in csv_files:
    df = pd.read_csv(csv_file)
    frdTrns_data.append(df)

# Concatenate all DataFrames in the list into a single DataFrame
final_df = pd.concat(frdTrns_data, ignore_index=True)

In [26]:
file1 = pd.read_csv(r'C:\\Users\\Sahil Khan\\OneDrive\Desktop\AI GRAD CERT\\aidi github\AIDI 2005 - Capstone Project II\\Fraud-Detection-in-Financial-Transactions\\Data\\output_file_1.csv')

In [27]:
file2 = pd.read_csv(r'C:\\Users\\Sahil Khan\\OneDrive\Desktop\AI GRAD CERT\\aidi github\AIDI 2005 - Capstone Project II\\Fraud-Detection-in-Financial-Transactions\\Data\\output_file_2.csv')

In [28]:
file1.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [29]:
file2.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,10,CASH_OUT,578570.34,C1842020389,0.00,0.00,C1750350389,782692.89,1735465.73,0,0
1,10,PAYMENT,3948.26,C924595278,0.00,0.00,M1742045918,0.00,0.00,0,0
2,10,PAYMENT,1990.85,C164024007,10117.51,8126.67,M1018772978,0.00,0.00,0,0
3,10,PAYMENT,3233.27,C1783742575,8126.67,4893.40,M559512713,0.00,0.00,0,0
4,10,CASH_IN,43526.60,C508964499,36522.00,80048.60,C1329428979,32187.91,0.00,0,0